version: '3'
services:
  web:
    build:
      context: web
    volumes:
      - ./web/bin:/var/www
    ports:
        - "80:80"
    depends_on:
      - maria
    links:
      - "maria:maria"

  maria:
    image: dolthub/dolt-sql-server
    ports:
      - 3306
    volumes:
      - ./maria/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - ./maria/dump-db.sql:/usr/local/dump-db.sql
